Repository DIT112-V19/group-04, pull requests merged in 2019-06, with the labels that each got.

#80 Arduino pathfinder communication
  arduino/testCar/bluetooth.cpp
  arduino/testCar/bluetooth.h
  arduino/testCar/constants.h
  arduino/testCar/pathfinder.cpp
  arduino/testCar/pathfinder.h
  arduino/testCar/point.cpp
  arduino/testCar/point.h
  arduino/testCar/testCar.ino
  server/entities/car.py
  server/entities/carpool.py
  server/main.py
  server/utils/bluetooth/config.yaml
  server/utils/bluetooth/serial_connection.py
  server/utils/simulator/car_mover.py
  server/utils/simulator/simulator.py
Labels: microcontroller, server-side, sprint #8

#79 Hot fix.ios client
  app/CarInterface/httpManager.swift
Labels: sprint #8

#83 Arduino pathfinder final product
  arduino/testCar/constants.h
  arduino/testCar/pathfinder.cpp
  arduino/testCar/pathfinder.h
  arduino/testCar/testCar.ino
  server/main.py
  server/utils/bluetooth/config.yaml
  server/utils/bluetooth/serial_connection.py
  server/utils/simulator/simulator.py
Labels: microcontroller, sprint #8
