Repository DIT112-V19/group-04, pull requests merged in 2019-04, with the labels that each got.

#6 initial commit for basic obstacle avoidance on the arudino
  README.md
  arduino/obstacleAvoidance/constants.h
  arduino/obstacleAvoidance/obstacleAvoidance.ino
  arduino/obstacleAvoidance/usedpins.h
Labels: sprint #1

#10 Add templates
  arduino/.github/ISSUE_TEMPLATE.md
  arduino/.github/PULL_REQUEST_TEMPLATE.md
  docs/ISSUE_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: sprint #1

#17 Server software
  server/vehicle management/carsharing.py
  server/vehicle management/coordinate.py
  server/vehicle management/simulator/simulator.py
  server/vehicle management/vector.py
  server/vehicle management/vehicle.py
Labels: sprint #3

#13 Initial commit for commanding the SmartCar from server
  .gitignore
  arduino/obstacleAvoidance/obstacleAvoidance.ino
  server/Makefile
  server/__init__.py
  server/application/__init__.py
  server/application/app.py
  server/bluetooth/__init__.py
  server/bluetooth/config.yaml
  server/bluetooth/serial_connection.py
  server/confighandler/__init__.py
  server/confighandler/yamlparser.py
  server/requirements.txt
Labels: sprint #2
