Repository DIT112-V19/group-04, pull requests merged in 2019-05, with the labels that each got.

#24 fixes #19
  server/application/app.py
Labels: sprint #4

#26 Add pathfinding Fixes #25
  server/vehicle management/pathfinding/astar.py
  server/vehicle management/pathfinding/map.py
  server/vehicle management/pathfinding/node.py
Labels: sprint #4

#27 Restructuring server folder and removed unneccessary files
  .gitignore
  server/Makefile
  server/__init__.py
  server/application/__init__.py
  server/bluetooth/__init__.py
  server/bluetooth/yamlparser.py
  server/confighandler/__init__.py
  server/main.py
  server/vehicle_management/carsharing.py
  server/vehicle_management/coordinate.py
  server/vehicle_management/pathfinding/astar.py
  server/vehicle_management/pathfinding/map.py
  server/vehicle_management/pathfinding/node.py
  server/vehicle_management/simulator/simulator.py
  server/vehicle_management/vector.py
  server/vehicle_management/vehicle.py
Labels: sprint #5

#23 #21 Add a map screen to the app
  app/CarInterface.xcodeproj/project.pbxproj
  app/CarInterface/Base.lproj/Main.storyboard
  app/CarInterface/Info.plist
  app/CarInterface/ViewController.swift
Labels: sprint #4

#29 Preparing the server for multiple users
  server/README.md
  server/bluetooth/__init__.py
  server/bluetooth/serial_connection.py
  server/bluetooth/yamlparser.py
  server/entities/__init__.py
  server/entities/car.py
  server/entities/carpool.py
  server/entities/user.py
  server/main.py
  server/requirements.txt
  server/utils/__init__.py
  server/utils/bluetooth/__init__.py
  server/utils/bluetooth/config.yaml
  server/utils/bluetooth/serial_connection.py
  server/utils/coordinate.py
  server/utils/vehicle_management/__init__.py
  server/utils/vehicle_management/carsharing.py
  server/utils/vehicle_management/pathfinding/__init__.py
  server/utils/vehicle_management/pathfinding/astar.py
  server/utils/vehicle_management/pathfinding/map.py
  server/utils/vehicle_management/pathfinding/node.py
  server/utils/vehicle_management/simulator/__init__.py
  server/utils/vehicle_management/simulator/simulator.py
  server/vehicle_management/coordinate.py
  server/vehicle_management/vector.py
Labels: server-side, sprint #5

#34 Map creator software
  server/entities/car.py
  server/entities/carpool.py
  server/requirements.txt
  server/utils/coordinate.py
  server/utils/map_creator/map.png
  server/utils/map_creator/map.py
  server/utils/map_creator/map.txt
  server/utils/map_creator/mapcreator.py
  server/utils/pathfinding/__init__.py
  server/utils/pathfinding/astar.py
  server/utils/simulator/__init__.py
  server/utils/simulator/simulator.py
  server/utils/vector.py
  server/utils/vehicle_management/carsharing.py
  server/utils/vehicle_management/pathfinding/node.py
  server/utils/vehicle_management/simulator/__init__.py
Labels: sprint #5

#37 Server things
  server/entities/carpool.py
  server/utils/map_creator/map.png
  server/utils/map_creator/map.py
  server/utils/map_creator/map.txt
  server/utils/map_creator/mapcreator.py
  server/utils/pathfinding/astar.py
  server/utils/simulator/simulator.py
Labels: feature, sprint #5

#41 Improved pickup logic
  server/entities/carpool.py
  server/main.py
  server/utils/map-creator/map.png
  server/utils/map-creator/map.py
  server/utils/map-creator/map.txt
  server/utils/map-creator/mapcreator.py
  server/utils/nodefinder.py
Labels: sprint #6

#63 initial commit for the pathfinder
  arduino/testCar/bluetooth.cpp
  arduino/testCar/bluetooth.h
  arduino/testCar/pathfinder.cpp
  arduino/testCar/pathfinder.h
  arduino/testCar/testCar.ino
Labels: sprint #6

#64 Arduino pathfinder
  arduino/testCar/constants.h
  arduino/testCar/pathfinder.cpp
  arduino/testCar/pathfinder.h
  arduino/testCar/testCar.ino
  arduino/testCar/usedpins.h
Labels: sprint #6

#68 Server refactoring
  README.md
  server/README.md
  server/entities/car.py
  server/entities/carpool.py
  server/main.py
  server/utils/mapcreator/map.py
  server/utils/nodefinder.py
  server/utils/pathfinding/astar.py
  server/utils/simulator/car_mover.py
  server/utils/vector.py
Labels: server-side, sprint #7
